---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 2

clone:
  disable: true

steps:
- name: git
  pull: if-not-exists
  image: plugins/git
  settings:
    tags: true

- name: run-tests
  pull: if-not-exists
  image: lustefaniak/sbt:adoptopenjdk8_1.4.1_2.13.3
  commands:
  - sbt -mem 2048 -Dcoursier.cache=/cache/.coursier/ -Dsbt.ivy.home=/cache/.ivy2/ -Divy.home=/cache/.ivy2/ -Dfile.encoding=utf-8 scalafmtCheckAll +test
  volumes:
  - name: sbt-cache
    path: /cache
  when:
    event:
    - pull_request

- name: publish-on-tag
  pull: if-not-exists
  image: lustefaniak/sbt:adoptopenjdk8_1.4.1_2.13.3
  commands:
  - sbt -mem 2048 -Dcoursier.cache=/cache/.coursier/ -Dsbt.ivy.home=/cache/.ivy2/ -Divy.home=/cache/.ivy2/ -Dfile.encoding=utf-8 +publish
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes:
  - name: sbt-cache
    path: /cache
  when:
    event:
    - tag

- name: publish-on-branch
  pull: if-not-exists
  image: lustefaniak/sbt:adoptopenjdk8_1.4.1_2.13.3
  commands:
  - sbt -mem 2048 -Dcoursier.cache=/cache/.coursier/ -Dsbt.ivy.home=/cache/.ivy2/ -Divy.home=/cache/.ivy2/ -Dfile.encoding=utf-8 +publish
  environment:
    GITHUB_TOKEN:
      from_secret: github_token
  volumes:
  - name: sbt-cache
    path: /cache
  when:
    event:
    - push

volumes:
- name: sbt-cache
  host:
    path: /var/lib/docker/sbt
